# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [1]:
#подключение пакета
import numpy as np
np.zeros(100, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 2.Создать вектор размера 100, заполненный единицами

In [2]:
np.ones(100, dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### 3.Создать вектор размера 100, заполненный числом 3

In [4]:
np.linspace(3,3,100, dtype = int)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [16]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 5. Поменять 2 строки в матрице

In [2]:
import numpy as np

arr = np.arange(4).reshape(2,2)
arr[[0,1]] = arr[[1,0]]
print(arr)

[[2 3]
 [0 1]]


#### 6. Создать вектор со значениями от 10 до 100

In [5]:
np.arange(10, 101)

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### 7. Развернуть вектор (первый становится последним)

In [3]:
import numpy as np
a = np.arange(10)
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [8]:
#создать матрицу 4 на 4 для 17 элементов невозможно, поэтому матрица до 15
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [3]:
import numpy as np

#создаем вектор
arr = np.array([1,2,3,4,5])
#создаем нулевой массив, учитывая условие задачи
ar = np.zeros(len(arr) + (len(arr)-1)*3)
ar[::3+1] = arr
print(ar)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 10. Создать 3x3 единичную матрицу

In [9]:
np.ones((3,3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

#### 11. Создать массив 3x3x3 со случайными значениями

In [10]:
np.random.random((3,3,3))

array([[[0.82796261, 0.91946611, 0.26840865],
        [0.11436932, 0.6839344 , 0.78948876],
        [0.13211624, 0.46289363, 0.84748768]],

       [[0.3060976 , 0.14600174, 0.91701386],
        [0.37526006, 0.15890707, 0.94125697],
        [0.27572905, 0.21392473, 0.09494889]],

       [[0.40472305, 0.05940114, 0.29952366],
        [0.05759748, 0.38417561, 0.21160423],
        [0.0432299 , 0.87341441, 0.88622138]]])

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [7]:
arr = np.random.random((10, 10))
print (arr.min(), arr.max())

0.010742396666262644 0.9983320977112355


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [4]:
a = np.random.rand(30)
a.mean()

0.549362842492383

#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [26]:
arr = np.ones((8,8), dtype = int)
arr[1:-1,1:-1] = 0
arr

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [10]:
#k<0 - под главной диагональю
np.diag([1,2,2,4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [12]:
#создаем нулевой массив 8х8
arr = np.zeros((8,8), dtype = int)

#указываем, что на каждом пересечении четной строки и четного столбца стоит 1
arr[::2,::2] = 1
#указываем, что на каждом пересечении нечетной строки и нечетного столбца стоит 1
arr[1::2, 1::2] = 1
arr

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [3]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [27]:
arr = np.array([1,0,0,1]).reshape(2, 2)
np.tile(arr, (4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Перемножить матрицы 5x3 и 3x2

In [15]:
A = np.random.random((5,3))
B = np.random.random((3,2))
A.dot(B)

array([[0.89999496, 0.96310172],
       [0.61580483, 0.73596772],
       [0.89703578, 0.93952573],
       [0.4324602 , 0.52129498],
       [1.28160222, 1.40027875]])

#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [11]:
arr = np.arange(10)
for i in arr :
    if (i > 3) and (i < 8) :
        arr[i] = -arr[i]
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [14]:
#создаем массив, состоящий только из 0
arr = np.zeros((5,5), dtype = int)
arr += np.arange(5)
arr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 24. Есть генератор, сделать с его помощью массив

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [4]:
#[1:-1] исключает 0 и 1
arr = np.linspace(0,1,12)[1:-1]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 26. Отсортировать вектор

In [6]:
print(np.random.random(5).sort())

None


#### 27. Проверить, одинаковы ли 2 numpy массива

In [5]:
arr1 = np.arange(8)
arr2 = np.arange(8)
arr3 = np.arange(9)
print(np.array_equal(arr1, arr2))
print(np.array_equal(arr1, arr3))

True
False


#### 28. Сделать массив неизменяемым

In [7]:
#создаем массив
arr = np.ones(5, dtype = int)
#false блокирует данные, делая их только доступными для чтения
arr.flags.writeable = False
#если попробовать изменить данные, то возникнет ошибка 
arr[2] = 0

ValueError: assignment destination is read-only

#### 29. Найти n наибольших значений в массиве

In [5]:
arr = np.arange(100)
print (arr[np.argpartition(-arr,3)][:3])

[98 99 97]


#### 30. Заменить максимальный элемент на ноль

In [8]:
#создаем массив 
arr = np.arange(10)
#находим индекс максимального элемента и заменяем в массиве на 0
arr[arr.argmax()] = 0
#проверяем, что значение поменялось
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 0])

#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [7]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 34. Напечатать все значения в массиве

In [13]:
#функция set_printoptions позволяет печатать значения, а не заменять их на ....
np.set_printoptions(threshold=5000)
arr = np.arange(1000, dtype = int).reshape(10, 100)
print(arr)

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
   36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
   54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
   72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
   90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
  136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
  154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
  172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
  190 191 192 193 194 195 196 197 198 199]
 [200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217
  218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235
  236 237 238 239 240 241 

#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [8]:
arr = np.arange(25)
num = np.random.uniform(0,25)
print(num)
index = (np.abs(arr-num)).argmin()
print(arr[index])

18.645767384146104
19


#### 36. Преобразовать массив из float в int

In [9]:
np.ones(10, dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### 37. Каков эквивалент функции enumerate для numpy массивов?

#### 38. Случайно расположить p элементов в 2D массив

In [9]:
arr = np.zeros((20, 20))
np.put(arr, np.random.choice(range(20*20), 5, replace=False), 1)

#### 39. Отнять среднее из каждой строки в матрице

In [10]:
#создаем массив
arr = np.arange(25).reshape(5,5)
#находим среднее значение
med = arr.mean()
#проходимся по каждой строке и вычитаем среднее
for i in range(len(arr)):
    arr[i,] = arr[i,] - med
arr

array([[-12, -11, -10,  -9,  -8],
       [ -7,  -6,  -5,  -4,  -3],
       [ -2,  -1,   0,   1,   2],
       [  3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12]])

#### 40. Отсортировать матрицу по n-ому столбцу

In [13]:
arr = np.random.randint(0,30,(5,5))
print(arr)
arr[arr[:,2].argsort()]

[[17  7 12  6  0]
 [26 22 17  4 13]
 [19  7  3  1 25]
 [28 29  1 23 22]
 [26  6 29 16  5]]


array([[28, 29,  1, 23, 22],
       [19,  7,  3,  1, 25],
       [17,  7, 12,  6,  0],
       [26, 22, 17,  4, 13],
       [26,  6, 29, 16,  5]])

#### 41. Определить, есть ли в 2D массиве нулевые столбцы

#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям